# Generated by Django 4.2.26 on 2025-12-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.IntegerField(choices=[(0, 'ANY'), (1, 'ACTION'), (2, 'ACTION ADVENTURE'), (3, 'JRPG'), (4, 'RPG'), (5, 'SIMULATION'), (6, 'STRATEGY'), (7, 'SPORTS')], default=0)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('game_developer', models.CharField(blank=True, max_length=200)),
                ('current_status', models.IntegerField(choices=[(0, 'COMPLETED'), (1, 'CURRENTLY_PLAYING'), (2, 'ON_HOLD'), (3, 'DROPPED'), (4, 'PLAN_TO_PLAY'), (5, 'NOT_PLAYED_YET')], default=4)),
                ('platform_of_choice', models.IntegerField(choices=[(0, 'PC'), (1, 'PLAYSTATION 5'), (2, 'PLAYSTATION 4'), (3, 'XBOX SERIES X'), (4, 'XBOX ONE'), (5, 'NINTENDO SWITCH'), (6, 'NINTEDO SWITCH 2'), (7, 'PLAYSTATION VITA'), (8, 'OTHER')], default=8)),
                ('hours_played', models.IntegerField(choices=[(0, '0-10'), (1, '10-50'), (2, '50-100'), (3, '100-200'), (4, '200+')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
